const cardDeck = [
    {
      name: "A Picche",
      value: 14,
      suit: 'P',
      image: 'Asso_di_picche',
      url: '40_Asso_di_picche.jpg',
      color: 'black',
    },
    {
      name: "2 Picche",
      value: 2,
      suit: 'P',
      image: 'Due_di_picche',
      url: '41_Due_di_picche.jpg',
      color: 'black',
    },
    {
      name: "3 Picche",
      value: 3,
      suit: 'P',
      image: 'Tre_di_picche',
      url: '42_Tre_di_picche.jpg',
      color: 'black',
    },
    {
      name: "4 Picche",
      value: 4,
      suit: 'P',
      image: 'Quattro_di_picche',
      url: '43_Quattro_di_picche.jpg',
      color: 'black',
    },
    {
      name: "5 Picche",
      value: 5,
      suit: 'P',
      image: 'Cinque_di_picche',
      url: '44_Cinque_di_picche.jpg',
      color: 'black',
    },
    {
      name: "6 Picche",
      value: 6,
      suit: 'P',
      image: 'Sei_di_picche',
      url: '45_Sei_di_picche.jpg',
      color: 'black',
    },
    {
      name: "7 Picche",
      value: 7,
      suit: 'P',
      image: 'Sette_di_picche',
      url: '46_Sette_di_picche.jpg',
      color: 'black',
    },
    {
      name: "8 Picche",
      value: 8,
      suit: 'P',
      image: 'Otto_di_picche',
      url: '47_Otto_di_picche.jpg',
      color: 'black',
    },
    {
      name: "9 Picche",
      value: 9,
      suit: 'P',
      image: 'Nove_di_picche',
      url: '48_Nove_di_picche.jpg',
      color: 'black',
    },
    {
      name: "10 Picche",
      value: 10,
      suit: 'P',
      image: 'Dieci_di_picche',
      url: '49_Dieci_di_picche.jpg',
      color: 'black',
    },
    {
      name: "J Picche",
      value: 11,
      suit: 'P',
      image: 'J_di_picche',
      url: '50_J_di_picche.jpg',
      color: 'black',
    },
    {
      name: "Q Picche",
      value: 12,
      suit: 'P',
      image: 'Q_di_picche',
      url: '51_Q_di_picche.jpg',
      color: 'black',
    },
    {
      name: "K Picche",
      value: 13,
      suit: 'P',
      image: 'K_di_picche',
      url: '52_K_di_picche.jpg',
      color: 'black',
    },
    {
      name: "A Cuori",
      value: 14,
      suit: 'C',
      image: 'Asso_di_cuori',
      url: '01_Asso_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "2 Cuori",
      value: 2,
      suit: 'C',
      image: 'Due_di_cuori',
      url: '02_Due_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "3 Cuori",
      value: 3,
      suit: 'C',
      image: 'Tre_di_cuori',
      url: '03_Tre_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "4 Cuori",
      value: 4,
      suit: 'C',
      image: 'Quattro_di_cuori',
      url: '04_Quattro_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "5 Cuori",
      value: 5,
      suit: 'C',
      image: 'Cinque_di_cuori',
      url: '05_Cinque_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "6 Cuori",
      value: 6,
      suit: 'C',
      image: 'Sei_di_cuori',
      url: '06_Sei_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "7 Cuori",
      value: 7,
      suit: 'C',
      image: 'Sette_di_cuori',
      url: '07_Sette_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "8 Cuori",
      value: 8,
      suit: 'C',
      image: 'Otto_di_cuori',
      url: '08_Otto_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "9 Cuori",
      value: 9,
      suit: 'C',
      image: 'Nove_di_cuori',
      url: '09_Nove_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "10 Cuori",
      value: 10,
      suit: 'C',
      image: 'Dieci_di_cuori',
      url: '10_Dieci_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "J Cuori",
      value: 11,
      suit: 'C',
      image: 'J_di_cuori',
      url: '11_J_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "Q Cuori",
      value: 12,
      suit: 'C',
      image: 'Q_di_cuori',
      url: '12_Q_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "K Cuori",
      value: 13,
      suit: 'C',
      image: 'K_di_cuori',
      url: '13_K_di_cuori.jpg',
      color: 'red',
    },
    {
      name: "A Quadri",
      value: 14,
      suit: "Q",
      image: 'Asso_di_quadri',
      url: '14_Asso_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "2 Quadri",
      value: 2,
      suit: "Q",
      image: 'Due_di_quadri',
      url: '15_Due_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "3 Quadri",
      value: 3,
      suit: "Q",
      image: 'Tre_di_quadri',
      url: '16_Tre_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "4 Quadri",
      value: 4,
      suit: "Q",
      image: 'Quattro_di_quadri',
      url: '17_Quattro_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "5 Quadri",
      value: 5,
      suit: "Q",
      image: 'Cinque_di_quadri',
      url: '18_Cinque_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "6 Quadri",
      value: 6,
      suit: "Q",
      image: 'Sei_di_quadri',
      url: '19_Sei_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "7 Quadri",
      value: 7,
      suit: "Q",
      image: 'Sette_di_quadri',
      url: '20_Sette_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "8 Quadri",
      value: 8,
      suit: "Q",
      image: 'Otto_di_quadri',
      url: '21_Otto_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "9 Quadri",
      value: 9,
      suit: "Q",
      image: 'Nove_di_quadri',
      url: '22_Nove_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "10 Quadri",
      value: 10,
      suit: "Q",
      image: 'Dieci_di_quadri',
      url: '23_Dieci_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "J Quadri",
      value: 11,
      suit: "Q",
      image: 'J_di_quadri',
      url: '24_J_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "Q Quadri",
      value: 12,
      suit: "Q",
      image: 'Q_di_quadri',
      url: '25_Q_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "K Quadri",
      value: 13,
      suit: "Q",
      image: 'K_di_quadri',
      url: '26_K_di_quadri.jpg',
      color: 'red',
    },
    {
      name: "A Fiori",
      value: 14,
      suit: "F",
      image: 'Asso_di_fiori',
      url: '27_Asso_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "2 Fiori",
      value: 2,
      suit: "F",
      image: 'Due_di_fiori',
      url: '28_Due_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "3 Fiori",
      value: 3,
      suit: "F",
      image: 'Tre_di_fiori',
      url: '29_Tre_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "4 Fiori",
      value: 4,
      suit: "F",
      image: 'Quattro_di_fiori',
      url: '30_Quattro_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "5 Fiori",
      value: 5,
      suit: "F",
      image: 'Cinque_di_fiori',
      url: '31_Cinque_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "6 Fiori",
      value: 6,
      suit: "F",
      image: 'Sei_di_fiori',
      url: '32_Sei_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "7 Fiori",
      value: 7,
      suit: "F",
      image: 'Sette_di_fiori',
      url: '33_Sette_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "8 Fiori",
      value: 8,
      suit: "F",
      image: 'Otto_di_fiori',
      url: '34_Otto_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "9 Fiori",
      value: 9,
      suit: "F",
      image: 'Nove_di_fiori',
      url: '35_Nove_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "10 Fiori",
      value: 10,
      suit: "F",
      image: 'Dieci_di_fiori',
      url: '36_Dieci_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "J Fiori",
      value: 11,
      suit: "F",
      image: 'J_di_fiori',
      url: '37_J_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "Q Fiori",
      value: 12,
      suit: "F",
      image: 'Q_di_fiori',
      url: '38_Q_di_fiori.jpg',
      color: 'black',
    }, 
    {
      name: "K Fiori",
      value: 13,
      suit: "F",
      image: 'K_di_fiori',
      url: '39_K_di_fiori.jpg',
      color: 'black',
    },
  ];

export default cardDeck;
